### PR TITLE
Review qna refined

### PR DESCRIPTION
**Pull request by friendlyantz**
# Pull Request
## Description :speak_no_evil:
ARCHITECTURE: Review model changed. migration files changed to accomodate ned review QnA
FEATURE: REVIEW optiomised to incl Amani's QnA's. form updated accordingly

ARCHITECTURE: PLACES-REVIEWS covid maths - added calculator to update PLACEs covid_score, once review submitted
Screen Shot 2020-12-03 at 7 20 50 pm

Screen Shot 2020-12-03 at 4 56 08 pm

## Commands to run
`rails db:drop
rails db:create
rails db:migrate
rails db:seed
`

		
## Changes :octopus:
- [x] **DB Migrations** 
- [x] **Controller** Reviews
- [x] **View** new Review
		
## How Has This Been Tested? :microscope:
- [x] rails c
- [x] Chrome

### CODE REVIEW

**Review by rycmak — CHANGES_REQUESTED** [review]
review.rb:
OPTIONS_5_STARS: change "Good" to have value 4 instead of 5

**Comment by friendlyantz** [comment]
ARCHITECTURE: PLACES/REVIEWS covid maths - added calculator to update PLACEs covid_score, once review submitted
Screen Shot 2020-12-03 at 7 20 50 pm

**Review by rycmak — CHANGES_REQUESTED** [review]
In `seeds.rb`, should we generate random review ratings as `rand(0..5)` instead of `rand(1..5)`, since in `review.rb` some of the answer options allow 0?

**Comment by friendlyantz** [comment]
> ARCHITECTURE: PLACES/REVIEWS covid maths - added calculator to update PLACEs covid_score, once review submitted
> Screen Shot 2020-12-03 at 7 20 50 pm
> 

Note for tomorrow morning - set up methods ,,(Universal method or class) for covid score
Masks, etc, etc.

**Comment by friendlyantz** [comment]
> In `seeds.rb`, should we generate random review ratings as `rand(0..5)` instead of `rand(1..5)`, since in `review.rb` some of the answer options allow 0?

I set up 1 - 5 as actual selections, with 0 reserved for unanswered. Let's discuss tomorrow!

**Review by rycmak — CHANGES_REQUESTED** [review]
In `reviews.rb`:
Making 11 SQL queries to calculate one score every time a review is submitted may be inefficient for large databases.
Try this instead:
`@place.covid_score = (@place.reviews.count * @place.covid_score + @review.covid_rating) / (@place.reviews.count + 1)`

This should give the same result.

**Comment by friendlyantz** [comment]
> In `reviews.rb`:
> Making 11 SQL queries to calculate one score every time a review is submitted may be inefficient for large databases.
> Try this instead:
> `@place.covid_score = (@place.reviews.count * @place.covid_score + @review.covid_rating) / (@place.reviews.count + 1)`
> 
> This should give the same result.

Thank you for the hint! but it doesnt work in app / corrupting calcs in rails.
will get back to this formula / methods later on. want to make something working and robust, even if it's not optimised!

**Review by rycmak — APPROVED** [review]

**Pull request merged**
